[[redirects]]
from = "/api/*"
to = "https://ieeesbbackend.herokuapp.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/upload/*"
to = "https://ieeesbbackend.herokuapp.com/upload/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
